### ISSUE TITLE
Getting $document is undefined error.

### ISSUE THREAD

**Issue by vinaydasari** [twhitbeck/angular-click-outside#3]
Hi there,

when the handler is removed we are trying to execute $document.off('click', eventHandler);
But in the current version, $document is not injected. I see the source is updated and is merged to master. Could you please update package.json and release a new version, so I can use this?

Thanks

**Comment by twhitbeck** [comment]
Apologies for not getting this out there sooner. I just pushed `v.1.2.0` on npm.

**Comment by skylarmb** [comment]
FWIW to future googlers I was getting this because i just `bower install`ed it which resolves to 1.1.1. I specified `twhitbeck/angular-click-outside#master` and all is good now.

**Comment by twhitbeck** [comment]
sorry, never pushed new version for bower. I'll fix that (I wasn't expecting any bower users anymore)

**Comment by twhitbeck** [comment]
@skylarmb how did you bower install this package? I don't have it published to bower registry...

**Comment by skylarmb** [comment]
@twhitbeck you can `bower install` any arbitrary github repository. If you do not specify a tag or SHA when installing / saving it will default to the latest release, which on github is [1.1.1](https://github.com/twhitbeck/angular-click-outside/releases)

```
...
"angular-click-outside": "twhitbeck/angular-click-outside#^1.1.1"
...
```

It's ok, I am not expecting bower support either, don't worry about publishing it :P

All I needed to do was change this to 

```
...
"angular-click-outside": "twhitbeck/angular-click-outside#master"
...
```

**Comment by twhitbeck** [comment]
:+1:
