### ISSUE TITLE
License file missing

### ISSUE THREAD

**Issue by tobiasbueschel** [twhitbeck/angular-click-outside#4]
Hi @twhitbeck :wave:

thanks for your work :-) I noticed that the repo misses a license file, would you accept PRs for that? Also, is there a reason why you use `ISC` instead of `MIT`?

Thanks and cheers

**Comment by twhitbeck** [comment]
I think `npm init` defaulted to `ISC`. You can open a PR.

**Comment by tobiasbueschel** [comment]
Done! Cheerio 🎉
